[build]
  publish = "."
  command = "echo 'Static site - no build needed'"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "*.png"
  [headers.values]
    Content-Type = "image/png"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Content-Type = "image/jpeg"

[[headers]]
  for = "*.mp3"
  [headers.values]
    Content-Type = "audio/mpeg"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
